var BASE={
  equipos:[
    {
      'Código': 'CEN-016',
      'Denominación': 'SUPPLY  CHAIN',
      Tipo: 'Fan Coil',
      Potencia: 0,
      Refrigerante: 'AGUA',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Terminal',
      'Fecha Alta': '1975-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ED. CENTRAL',
      servicePoints: '["CEN-LS002","CEN-LS003","CEN-LS004","CEN-LS005","CEN-LS006"]',
      Activo: 'SI'
    },
    {
      'Código': 'SDC-007',
      'Denominación': 'NUEVA OFICINA BALANZA',
      Tipo: 'Split',
      Potencia: 4500,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '1994-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'SIDERCROM',
      servicePoints: '["SDC-LS007"]',
      Activo: 'SI'
    },
    {
      'Código': 'PSR-012',
      'Denominación': 'CABINA CONTROL DE CAMIONES - Nº4',
      Tipo: 'Split',
      Potencia: 3000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'PORTERIA SUR',
      servicePoints: '["PSR-LS011"]',
      Activo: 'SI'
    },
    {
      'Código': 'SVA-021',
      'Denominación': 'SALA VAI COSIM',
      Tipo: 'Autocontenido Cond. X Agua',
      Potencia: 45000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BIEN',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'SERVIACERO',
      servicePoints: '["SVA-LS017"]',
      Activo: 'SI'
    },
    {
      'Código': 'AH1-015',
      'Denominación': 'S.E. Nº 1 AH1',
      Tipo: 'Separado',
      Potencia: 30000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '1994-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'ALHOR 1',
      servicePoints: '["AH1-LS011"]',
      Activo: 'SI'
    },
    {
      'Código': 'COQ-090',
      'Denominación': 'S.E - OBRA 62',
      Tipo: 'Split',
      Potencia: 18000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'COQUERIA',
      servicePoints: '["COQ-LS059"]',
      Activo: 'SI'
    },
    {
      'Código': 'CC1-021',
      'Denominación': 'PULPITO DE CORTE CC1',
      Tipo: 'Fan Coil',
      Potencia: 0,
      Refrigerante: 'AGUA',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BIEN',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'ACERIA CC1',
      servicePoints: '["CC1-LS008","CC1-LS009"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAC-190',
      'Denominación': 'GRUA 43',
      Tipo: 'Mochila RITTAL',
      Potencia: 3000,
      Refrigerante: 'R-134a',
      'Detalles Extra': '',
      Servicio: 'GRUA',
      Estado: 'BUENO',
      'Categoría': 'Gruas C. Alterna',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Caloría',
      'Línea': 'CALIENTE',
      servicePoints: '["LAC-LS019"]',
      Activo: 'SI'
    },
    {
      'Código': 'COQ-067',
      'Denominación': 'OFICINA PREVENTIVO',
      Tipo: 'Split',
      Potencia: 15000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'COQUERIA',
      servicePoints: '["COQ-LS040"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-076',
      'Denominación': 'LABORATORIO LIMPIEZA ELECTROLITICA',
      Tipo: 'Split',
      Potencia: 4500,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'PULPITO',
      Estado: 'BUENO',
      'Categoría': 'Pulpito',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS062"]',
      Activo: 'SI'
    },
    {
      'Código': 'SIS-001',
      'Denominación': 'ENFRIADOR DE AGUA - SISTEMAS',
      Tipo: 'Autocontenido Cond. X Agua',
      Potencia: 0,
      Refrigerante: 'R-22',
      'Detalles Extra': '45TR',
      Servicio: 'PULPITO',
      Estado: 'BUENO',
      'Categoría': 'Maquinas Pesadas',
      'Fecha Alta': '1975-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ED. SISTEMA',
      servicePoints: '["SIS-LS001"]',
      Activo: 'SI'
    },
    {
      'Código': 'CC2-012',
      'Denominación': 'S.E. PLC HOUSE 3',
      Tipo: 'Tecno',
      Potencia: 60000,
      Refrigerante: 'R-134a',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2013-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'ACERIA CC2',
      servicePoints: '["CC2-LS007"]',
      Activo: 'SI'
    },
    {
      'Código': 'COQ-070',
      'Denominación': 'OFICINA TECNICA BATERIAS 3 y 4',
      Tipo: 'Split',
      Potencia: 15000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'COQUERIA',
      servicePoints: '["COQ-LS046"]',
      Activo: 'SI'
    },
    {
      'Código': 'ALD-082',
      'Denominación': 'PULPITO OPERADOR CONVERTIDOR Nº2',
      Tipo: 'Tecno',
      Potencia: 6000,
      Refrigerante: 'R-134a',
      'Detalles Extra': '',
      Servicio: 'PULPITO',
      Estado: 'BUENO',
      'Categoría': 'Pulpito',
      'Fecha Alta': '2017-03-01 00:00:00',
      Ambiente: 'Polución + Caloría',
      'Línea': 'ACERIA LD',
      servicePoints: '["ALD-LS039"]',
      Activo: 'SI'
    },
    {
      'Código': 'CAP-017',
      'Denominación': 'COCINA CAPACITACION',
      Tipo: 'Split',
      Potencia: 4500,
      Refrigerante: 'R-410',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2014-11-10 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ED. CAPACITACION',
      servicePoints: '["CAP-LS018"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-036',
      'Denominación': 'OFICINA DESPACHO PORTON 116',
      Tipo: 'Compacto',
      Potencia: 3000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS029"]',
      Activo: 'SI'
    },
    {
      'Código': 'ALD-045',
      'Denominación': 'PULPITO CALCINACION',
      Tipo: 'Fan Coil',
      Potencia: 0,
      Refrigerante: 'AGUA',
      'Detalles Extra': '',
      Servicio: 'PULPITO',
      Estado: 'BUENO',
      'Categoría': 'Pulpito',
      'Fecha Alta': '1984-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'ACERIA LD',
      servicePoints: '["ALD-LS016"]',
      Activo: 'SI'
    },
    {
      'Código': 'ENE-045',
      'Denominación': 'TANQUE CO2  CETE 2',
      Tipo: 'Tecno',
      Potencia: 15000,
      Refrigerante: 'R-404',
      'Detalles Extra': '',
      Servicio: 'PULPITO',
      Estado: 'BIEN',
      'Categoría': 'Maquinas Pesadas',
      'Fecha Alta': '2008-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ENERGIA',
      servicePoints: '["ENE-LS029"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-034',
      'Denominación': 'PULPITO CONTROL SOLUCION DECAPADO',
      Tipo: 'Split',
      Potencia: 9000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'PULPITO',
      Estado: 'BUENO',
      'Categoría': 'Pulpito',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS027"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAQ-015',
      'Denominación': 'OFICINA JEFE',
      Tipo: 'Split',
      Potencia: 4500,
      Refrigerante: 'R-410',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ED. LAQUIME',
      servicePoints: '["LAQ-LS005"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAC-030',
      'Denominación': 'GRUA 43',
      Tipo: 'Linter CA',
      Potencia: 4500,
      Refrigerante: 'R-134a',
      'Detalles Extra': '',
      Servicio: 'GRUA',
      Estado: 'BUENO',
      'Categoría': 'Gruas C. Alterna',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Caloría',
      'Línea': 'CALIENTE',
      servicePoints: '["LAC-LS019"]',
      Activo: 'SI'
    },
    {
      'Código': 'PUE-029',
      'Denominación': 'GRUA MAND 2',
      Tipo: 'Split',
      Potencia: 9000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'GRUA',
      Estado: 'BUENO',
      'Categoría': 'Gruas C. Alterna',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'PUERTO',
      servicePoints: '["PUE-LS023"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-038',
      'Denominación': 'ENFRIADOR DE AGUA - GERENCIA FRIO',
      Tipo: 'Bomba',
      Potencia: 0,
      Refrigerante: 'AGUA',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Maquinas Pesadas',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS030"]',
      Activo: 'SI'
    },
    {
      'Código': 'ALD-168',
      'Denominación': 'S.E. PLANTA DE AGUA',
      Tipo: 'Tecno',
      Potencia: 22500,
      Refrigerante: 'R-134a',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BIEN',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2014-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ACERIA LD',
      servicePoints: '["ALD-LS029"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-153',
      'Denominación': 'SALA ELECTRICA LIF',
      Tipo: 'Split',
      Potencia: 15000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '1994-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS131"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-115',
      'Denominación': 'S.E. - ESTAÑADO ELECTROLITICO',
      Tipo: 'Roof Top',
      Potencia: 90000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS097"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAQ-009',
      'Denominación': 'ENFRIADOR DE AGUA - LAQUIME',
      Tipo: 'Bomba',
      Potencia: 0,
      Refrigerante: 'AGUA',
      'Detalles Extra': '',
      Servicio: 'PULPITO',
      Estado: 'BUENO',
      'Categoría': 'Maquinas Pesadas',
      'Fecha Alta': '1975-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ED. LAQUIME',
      servicePoints: '["LAQ-LS001"]',
      Activo: 'SI'
    },
    {
      'Código': 'ALD-134',
      'Denominación': 'S.E CCM 34/35',
      Tipo: 'Tecno',
      Potencia: 15000,
      Refrigerante: 'R-134a',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2016-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'ACERIA LD',
      servicePoints: '["ALD-LS014"]',
      Activo: 'SI'
    },
    {
      'Código': 'CC2-036',
      'Denominación': 'SALA RACK PLC DE MOLDES',
      Tipo: 'Split',
      Potencia: 9000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BIEN',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2017-06-15 00:00:00',
      Ambiente: 'Polución + Caloría',
      'Línea': 'ACERIA CC2',
      servicePoints: '["CC2-LS023"]',
      Activo: 'SI'
    },
    {
      'Código': 'EDI-010',
      'Denominación': 'VESTUARIO OBRADORES (VILLA 31)',
      Tipo: 'Termotanque',
      Potencia: 0,
      Refrigerante: 'ELECTRICIDAD',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BIEN',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2015-11-11 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'EDIFICIO',
      servicePoints: '["EDI-LS007"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-054',
      'Denominación': 'GRUA 124',
      Tipo: 'Split',
      Potencia: 3000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'GRUA',
      Estado: 'BUENO',
      'Categoría': 'Gruas C. Alterna',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS042"]',
      Activo: 'SI'
    },
    {
      'Código': 'SIN-016',
      'Denominación': 'GRUA GT1',
      Tipo: 'Linter CA',
      Potencia: 21000,
      Refrigerante: 'R-134a',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Polución',
      'Línea': 'SINTER',
      servicePoints: '["SIN-LS009"]',
      Activo: 'SI'
    },
    {
      'Código': 'CC2-038',
      'Denominación': 'CABINA LINEA 3',
      Tipo: 'Split',
      Potencia: 6000,
      Refrigerante: 'R-410',
      'Detalles Extra': '',
      Servicio: 'PULPITO',
      Estado: 'BIEN',
      'Categoría': 'Pulpito',
      'Fecha Alta': '2016-12-01 00:00:00',
      Ambiente: 'Polución + Caloría',
      'Línea': 'ACERIA CC2',
      servicePoints: '["CC2-LS025"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAC-029',
      'Denominación': 'GRUA 107',
      Tipo: 'Split',
      Potencia: 4500,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'GRUA',
      Estado: 'BUENO',
      'Categoría': 'Gruas C. Alterna',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Caloría',
      'Línea': 'CALIENTE',
      servicePoints: '["LAC-LS018"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-119',
      'Denominación': 'S.E. - RECOCIDO 2',
      Tipo: 'Split',
      Potencia: 15000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Caloría',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS101"]',
      Activo: 'SI'
    },
    {
      'Código': 'CAP-010',
      'Denominación': 'CAPACITACION SALA AUDITORIO',
      Tipo: 'Roof Top',
      Potencia: 90000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Maquinas Pesadas',
      'Fecha Alta': '1999-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ED. CAPACITACION',
      servicePoints: '["CAP-LS010"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAC-143',
      'Denominación': 'COMEDOR DE CILINDROS',
      Tipo: 'Split',
      Potencia: 4500,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'MAL',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'CALIENTE',
      servicePoints: '["LAC-LS091"]',
      Activo: 'SI'
    },
    {
      'Código': 'COQ-048',
      'Denominación': 'DESHORNADORA 3',
      Tipo: 'Tecno',
      Potencia: 9000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'GRUA',
      Estado: 'BUENO',
      'Categoría': 'Carros',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Polución + Caloría',
      'Línea': 'COQUERIA',
      servicePoints: '["COQ-LS028"]',
      Activo: 'SI'
    },
    {
      'Código': 'TCE-010',
      'Denominación': 'OFICINA GMP',
      Tipo: 'Split',
      Potencia: 6000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BIEN',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'ED. TALLER CENTRAL',
      servicePoints: '["TCE-LS006"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-065',
      'Denominación': 'GRUA 192',
      Tipo: 'Split',
      Potencia: 4500,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'GRUA',
      Estado: 'BUENO',
      'Categoría': 'Gruas C. Alterna',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS053"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAC-171',
      'Denominación': 'SE - MESA ENFRIAMIENTO',
      Tipo: 'Compacto',
      Potencia: 6000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'SALA ELECTRICA',
      Estado: 'BUENO',
      'Categoría': 'Sala Electrica',
      'Fecha Alta': '1994-06-01 00:00:00',
      Ambiente: 'Caloría',
      'Línea': 'CALIENTE',
      servicePoints: '["LAC-LS035"]',
      Activo: 'SI'
    },
    {
      'Código': 'EXP-006',
      'Denominación': 'OFICINA COMPUTADORA EXPEDICION',
      Tipo: 'Split',
      Potencia: 15000,
      Refrigerante: 'R-410',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2004-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'EX  EXPEDICION',
      servicePoints: '["EXP-LS002"]',
      Activo: 'SI'
    },
    {
      'Código': 'LAF-028',
      'Denominación': 'CASILLA DE VIGILANCIA CHAPA NAVAL',
      Tipo: 'Split',
      Potencia: 3000,
      Refrigerante: 'R-22',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Equipos Menores',
      'Fecha Alta': '2009-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'FRIO',
      servicePoints: '["LAF-LS021"]',
      Activo: 'SI'
    },
    {
      'Código': 'EXP-003',
      'Denominación': 'F.SERV - EX EXPEDICION',
      Tipo: 'Torre',
      Potencia: 0,
      Refrigerante: 'AGUA',
      'Detalles Extra': '',
      Servicio: 'OFICINA',
      Estado: 'BUENO',
      'Categoría': 'Maquinas Pesadas',
      'Fecha Alta': '1975-06-01 00:00:00',
      Ambiente: 'Normal',
      'Línea': 'EX  EXPEDICION',
      servicePoints: '["EXP-LS001"]',
      Activo: 'SI'
    }
  ],
  OTs:[
      {
        'Código': '18399',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'SIN-027',
        'Lugar de Servicio': 'S.E. - VENTILADOR PRINCIPAL',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"4021"}',
        Registrado: '2016-11-19 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2016-11-20 05:18:11"}',
        Cierre: '{"Fecha":"2016-11-21 10:36:23","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '11793',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA TERMICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-021',
        'Lugar de Servicio': 'CARRO DE CARGA 5',
        Solicitante: '{"Nombre":"Manera","Teléfono":"3008"}',
        Registrado: '2015-05-14 00:00:00',
        Respuesta: '{"Interviniente":["FERNANDEZ","TARRAGONA"],"Fecha":"2015-05-14 20:47:03"}',
        Cierre: '{"Fecha":"2015-05-15 17:34:05","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MONAY, LEONARDO',
        'Causa General': 'TÉRMICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '17716',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 14001997,
        Equipo: 'ALD-160',
        'Lugar de Servicio': 'CALCINACION - PULPITO BARROS BLANCOS',
        Solicitante: '{"Nombre":"INTENDENCIA","Teléfono":"261*3183"}',
        Registrado: '2016-09-17 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","MENDOZA"],"Fecha":"2016-09-29 17:22:33"}',
        Cierre: '{"Fecha":"2016-10-12 10:45:06","Usuario":"FRANQUITO"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ING Y MTO',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '17666',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-026',
        'Lugar de Servicio': 'GRUA 103',
        Solicitante: '{"Nombre":"OVIEDO","Teléfono":"5840"}',
        Registrado: '2016-09-10 00:00:00',
        Respuesta: '{"Interviniente":["FEHR","LOPEZ A."],"Fecha":"2016-09-11 07:35:13"}',
        Cierre: '{"Fecha":"2016-09-12 15:10:26","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 1,
        'Tareas Pendientes': 'BAJAR EQ Y REALIZAR MTO, CAMBIAR VI',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '14664',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESMONTADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-171',
        'Lugar de Servicio': 'SE - MESA ENFRIAMIENTO',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2016-01-15 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","RIOS"],"Fecha":"2016-03-03 13:21:31"}',
        Cierre: '{"Fecha":"2016-04-21 02:43:02","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'MECÁNICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20873',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'MAR-012',
        'Lugar de Servicio': 'VESTUARIO MARE',
        Solicitante: '{"Nombre":"NOSEDA","Teléfono":"5853"}',
        Registrado: '2017-06-09 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2017-06-10 17:15:34"}',
        Cierre: '{"Fecha":"2017-06-12 10:31:08","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'NADA',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '11577',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-014',
        'Lugar de Servicio': 'SE - INSTRUMENTAL ENTRE HORNO 1 Y 2',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"4109"}',
        Registrado: '2015-04-18 00:00:00',
        Respuesta: '{"Interviniente":["ALVAREZ O.","LOPEZ A."],"Fecha":"2015-04-19 05:19:05"}',
        Cierre: '{"Fecha":"2015-04-20 10:38:10","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MONAY, LEONARDO',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '11910',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'PCN-002',
        'Lugar de Servicio': 'COMEDOR  CENTRAL  PERSONAL',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2015-05-20 00:00:00',
        Respuesta: '{"Interviniente":["CAMPILONGO","SERRANO"],"Fecha":"2015-05-23 17:36:30"}',
        Cierre: '{"Fecha":"2015-05-27 11:13:01","Usuario":"MALAMIA"}',
        Supervisor: 'MONAY, LEONARDO',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '18160',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-031',
        'Lugar de Servicio': 'CARRO GUIA 5',
        Solicitante: '{"Nombre":"LEGUIZAMO","Teléfono":"3836"}',
        Registrado: '2016-11-04 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","FEHR"],"Fecha":"2016-11-04 07:10:54"}',
        Cierre: '{"Fecha":"2016-11-04 14:21:49","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'NADA',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '12342',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'SIN-014',
        'Lugar de Servicio': 'GRUA GT1',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"3746"}',
        Registrado: '2015-07-20 00:00:00',
        Respuesta: '{"Interviniente":["FEHR","LOPEZ A."],"Fecha":"2015-07-23 16:43:01"}',
        Cierre: '{"Fecha":"2015-07-27 09:26:02","Usuario":"FRANQUITO"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'NADA',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '13669',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LME-001',
        'Lugar de Servicio': 'ENFRIADOR DE AGUA - METALOGRAFICO Y MASI',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"4111"}',
        Registrado: '2015-11-11 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2016-02-03 08:24:25"}',
        Cierre: '{"Fecha":"2016-04-27 16:48:51","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20069',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'PERDIDA DE AGUA',
        'Descripción': '',
        'OT Siderar': 14418233,
        Equipo: 'PSR-009',
        'Lugar de Servicio': 'OFICINA SEARCH PORTERIA SUR',
        Solicitante: '{"Nombre":"COTTINI","Teléfono":""}',
        Registrado: '2017-03-09 00:00:00',
        Respuesta: '{"Interviniente":["FLOREANI","ANTICHI"],"Fecha":"2017-03-09 07:47:12"}',
        Cierre: '{"Fecha":"2017-03-09 15:34:25","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'TÉRMICO',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '24839',
        Estado: 'Abierta',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'SE ENCUENTRA Y REPARA PERDIDA EN CODO DE ALTA DEL SISTEMA N°2 , AJUSTE DE REFRIGERANTE , CONTROL DE FUNCIONAMIENTO AL SISTEMA N°1.',
        'OT Siderar': 14734291,
        Equipo: 'INT-005',
        'Lugar de Servicio': 'INTENDENCIA PLANTA BAJA',
        Solicitante: '{"Nombre":"INTENDENCIA","Teléfono":"261*3183"}',
        Registrado: '2018-02-15 00:00:00',
        Respuesta: '{"Interviniente":["CAMPILONGO","GUERREIRO"],"Fecha":"1959-01-23 00:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 0,
        'Tareas Pendientes': 'FALTA AJUSTE DE REFRIGERANTE AL SIST. N°2.',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '16368',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 14059904,
        Equipo: 'COQ-033',
        'Lugar de Servicio': 'CARRO GUIA 5',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2016-05-04 00:00:00',
        Respuesta: '{"Interviniente":["ALVAREZ O.","FEHR"],"Fecha":"2016-05-12 03:27:22"}',
        Cierre: '{"Fecha":"2016-05-20 06:54:44","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 3,
        'Tareas Pendientes': 'CAMBIAR CONDENSADORA COMPLETA',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '22688',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': 'Se repone queda en servicio.',
        'OT Siderar': '',
        Equipo: 'LAC-163',
        'Lugar de Servicio': 'SALA ELECTRICA CONTACTORES RSB',
        Solicitante: '{"Nombre":"zabala","Teléfono":"574"}',
        Registrado: '2017-11-29 00:00:00',
        Respuesta: '{"Interviniente":["BADARACCO","BASUALDO"],"Fecha":"2017-11-29 00:00:00"}',
        Cierre: '{"Fecha":"2017-11-29 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '14363',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-031',
        'Lugar de Servicio': 'CARRO DE CARGA 4',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2015-12-29 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2016-02-24 01:50:05"}',
        Cierre: '{"Fecha":"2016-04-21 03:40:10","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '11200',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FILTROS DE AIRE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'CC1-036',
        'Lugar de Servicio': 'TALLER DE BAUMANN',
        Solicitante: '{"Nombre":"Bonetto","Teléfono":"4136"}',
        Registrado: '2015-03-17 00:00:00',
        Respuesta: '{"Interviniente":["GONZALEZ","BOGADO G."],"Fecha":"2015-04-24 17:07:34"}',
        Cierre: '{"Fecha":"2015-06-02 10:15:07","Usuario":"USUARIORANDOM"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'TÉRMICO',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '18980',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-085',
        'Lugar de Servicio': 'S.E. - ENFRIADORES PRIMARIOS 2 MC 16',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"2590"}',
        Registrado: '2016-12-23 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","GONZALEZ"],"Fecha":"2016-12-25 06:46:25"}',
        Cierre: '{"Fecha":"2016-12-27 13:32:51","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '23187',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'Se desmonta los filtros de aire y se sopletea, junto con el evaporador y el condensador. Se controlan las presione y las correas.',
        'OT Siderar': '',
        Equipo: '',
        'Lugar de Servicio': 'CARRO DE CARGA 4',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3183"}',
        Registrado: '2017-12-18 00:00:00',
        Respuesta: '{"Interviniente":["FABA","CORONEL"],"Fecha":"2017-12-18 00:00:00"}',
        Cierre: '{"Fecha":"2017-12-18 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '19696',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'TCE-018',
        'Lugar de Servicio': 'SALA REUNIONES (ex bobinado chico)',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"5870"}',
        Registrado: '2017-02-08 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PEREZ"],"Fecha":"2017-02-08 17:21:34"}',
        Cierre: '{"Fecha":"2017-02-09 10:43:08","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '23761',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': 'se habilita y se deja en servicio. Se limpian los filtros de aire.',
        'OT Siderar': '',
        Equipo: 'LAC-047',
        'Lugar de Servicio': 'PULPITO BOBINADORA',
        Solicitante: '{"Nombre":"supervisor","Teléfono":"5841"}',
        Registrado: '2018-01-22 00:00:00',
        Respuesta: '{"Interviniente":["PIERANI","GALASSI"],"Fecha":"2018-01-22 00:00:00"}',
        Cierre: '{"Fecha":"2018-01-22 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '16708',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'SIS-024',
        'Lugar de Servicio': 'EQUIPOS LIEBERT',
        Solicitante: '{"Nombre":"ESCALANTE","Teléfono":""}',
        Registrado: '2016-06-21 00:00:00',
        Respuesta: '{"Interviniente":["CAMPILONGO","PIERANI"],"Fecha":"2016-07-01 10:27:56"}',
        Cierre: '{"Fecha":"2016-07-11 20:55:53","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '24800',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': 'SE HABILITA QUEDA EN SERVICIO.',
        'OT Siderar': '',
        Equipo: 'SIN-003',
        'Lugar de Servicio': 'S.E. - CCM 2/3',
        Solicitante: '{"Nombre":"SUP.","Teléfono":"261*4021"}',
        Registrado: '2018-03-30 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2018-04-01 17:00:01"}',
        Cierre: '{"Fecha":"2018-04-04 10:00:02","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '14872',
        Estado: 'Cerrada',
        Clase: 'Preventivo',
        Causa: 'PREVENTIVO',
        'Descripción': 'OT 13927211',
        'OT Siderar': '',
        Equipo: 'SIN-027',
        'Lugar de Servicio': 'S.E. - VENTILADOR PRINCIPAL',
        Solicitante: '{"Nombre":"MONTINI","Teléfono":"4477"}',
        Registrado: '2015-11-05 00:00:00',
        Respuesta: '{"Interviniente":["ALVAREZ O.","UDUT"],"Fecha":"1957-12-02 12:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'ALVAREZ M., MAURICIO RAMON',
        'Causa General': 'PREVENCION',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '14107',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FALTA GAS REFRIGERANTE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'ALD-102',
        'Lugar de Servicio': 'GRUA 170',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"3937"}',
        Registrado: '2015-12-16 00:00:00',
        Respuesta: '{"Interviniente":["BADARACCO","BASUALDO"],"Fecha":"1957-12-23 00:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'ALVAREZ M., MAURICIO RAMON',
        'Causa General': 'TÉRMICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22892',
        Estado: 'Abierta',
        Clase: 'Reclamo',
        Causa: 'FALTA GAS REFRIGERANTE',
        'Descripción': 'Se completa carga de gas. Queda en servicio.',
        'OT Siderar': '',
        Equipo: 'SIN-030',
        'Lugar de Servicio': 'PULPITO CONTROL PRINCIPAL PLANTA NUEVA',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":"3746"}',
        Registrado: '2017-12-10 00:00:00',
        Respuesta: '{"Interviniente":["GONZALEZ","TARRAGONA"],"Fecha":"1958-12-20 12:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'TÉRMICO',
        Horas: 5,
        'Tareas Pendientes': 'ver q van hacer con el equipo.',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22442',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': 'Se habilita queda en servicio.',
        'OT Siderar': '',
        Equipo: 'LAF-099',
        'Lugar de Servicio': 'OFICINA SUPERVISOR ESTAÑADO',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":"5005"}',
        Registrado: '2017-11-09 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PIERANI"],"Fecha":"2017-11-09 00:00:00"}',
        Cierre: '{"Fecha":"2017-11-09 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22846',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': 'Se reajustan cables queda en servicio.',
        'OT Siderar': '',
        Equipo: 'CC1-028',
        'Lugar de Servicio': 'PULPITO LINEA 1 COLADA CONTINUA 1',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":"5877"}',
        Registrado: '2017-12-08 00:00:00',
        Respuesta: '{"Interviniente":["GONZALEZ","TARRAGONA"],"Fecha":"2017-12-08 00:00:00"}',
        Cierre: '{"Fecha":"2017-12-08 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20693',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'SIN-025',
        'Lugar de Servicio': 'SALA CONTROL PLANTA SINTER',
        Solicitante: '{"Nombre":"PEREYRA","Teléfono":"4021"}',
        Registrado: '2017-05-15 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","FEHR"],"Fecha":"2017-05-16 07:21:41"}',
        Cierre: '{"Fecha":"2017-05-17 14:43:23","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 5,
        'Tareas Pendientes': 'EQ SUCIO, HACER MTO TOGENTII EN TEMA',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '13037',
        Estado: 'Cerrada',
        Clase: 'Preventivo',
        Causa: 'PREVENTIVO',
        'Descripción': 'OT 13788293',
        'OT Siderar': '',
        Equipo: 'LAF-119',
        'Lugar de Servicio': 'S.E. - RECOCIDO 2',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":""}',
        Registrado: '2015-08-02 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","CORONEL"],"Fecha":"2015-08-31 20:25:29"}',
        Cierre: '{"Fecha":"2015-09-30 16:50:58","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'PREVENCION',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '19799',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-049',
        'Lugar de Servicio': 'DESHORNADORA 3',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"3836"}',
        Registrado: '2017-03-20 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","LARREA"],"Fecha":"2017-03-10 19:38:03"}',
        Cierre: '{"Fecha":"2017-03-01 15:16:07","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '15376',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FALTA GAS REFRIGERANTE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-135',
        'Lugar de Servicio': 'TABLEROS SILCO TERMINADORES',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2016-02-22 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","RIOS"],"Fecha":"2016-03-25 12:30:33"}',
        Cierre: '{"Fecha":"2016-04-27 01:01:07","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'TÉRMICO',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '11809',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LME-006',
        'Lugar de Servicio': 'CENTRAL LABORATORIO METALOGRAFICO',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"5548"}',
        Registrado: '2015-05-16 00:00:00',
        Respuesta: '{"Interviniente":["GOMEZ","GONZALEZ"],"Fecha":"2015-05-18 04:33:18"}',
        Cierre: '{"Fecha":"2015-05-20 09:06:37","Usuario":"FRANQUITO"}',
        Supervisor: 'MONAY, LEONARDO',
        'Causa General': 'ELÉCTRICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '14231',
        Estado: 'Cerrada',
        Clase: 'Preventivo',
        Causa: 'PREVENTIVO',
        'Descripción': 'OT 13945643',
        'OT Siderar': '',
        Equipo: 'AH2-004',
        'Lugar de Servicio': 'COMEDOR NUEVO AH2',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2015-12-23 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"1957-12-26 12:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'PREVENCION',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22410',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'Se desmonta evaporador y se hidrolava. El condensador se hidrolava en el lugar. Se cambia cableado de capacitor. Se monta evaporador. Queda en servicio.',
        'OT Siderar': '',
        Equipo: 'ENE-015',
        'Lugar de Servicio': 'S.E. - SOPLADORES ENERGIA',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3183"}',
        Registrado: '2017-06-24 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PIERANI"],"Fecha":"2017-06-24 00:00:00"}',
        Cierre: '{"Fecha":"2017-06-24 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'ING Y MTO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '17916',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'MANTENIMIENTO SIN OT SIDERAR',
        'OT Siderar': '',
        Equipo: 'COQ-096',
        'Lugar de Servicio': 'PLC SOPLADORES',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2016-09-22 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","BADARACCO"],"Fecha":"2016-09-29 17:46:54"}',
        Cierre: '{"Fecha":"2016-10-07 11:33:48","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '16537',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 14109774,
        Equipo: 'ALD-040',
        'Lugar de Servicio': 'S.E CCM 34/35',
        Solicitante: '{"Nombre":"Mainz","Teléfono":"3071"}',
        Registrado: '2016-05-31 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","LOPEZ A."],"Fecha":"2016-05-31 17:17:42"}',
        Cierre: '{"Fecha":"2016-06-01 10:35:24","Usuario":"MALAMIA"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'ING Y MTO',
        Horas: 2,
        'Tareas Pendientes': 'continuar con la reinstalacion',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '13962',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-020',
        'Lugar de Servicio': 'CARRO DE CARGA 5',
        Solicitante: '{"Nombre":"SOBERANO","Teléfono":""}',
        Registrado: '2015-12-06 00:00:00',
        Respuesta: '{"Interviniente":["FEHR","FERNANDEZ"],"Fecha":"2016-02-15 20:39:28"}',
        Cierre: '{"Fecha":"2016-04-27 17:18:56","Usuario":"MALAMIA"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'ELÉCTRICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '14200',
        Estado: 'Cerrada',
        Clase: 'Preventivo',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'OT 14015021 - NORMALIZAR FUNCIONAMIENTO',
        'OT Siderar': '',
        Equipo: 'ALD-061',
        'Lugar de Servicio': 'OFICINA TALLER ZONAL',
        Solicitante: '{"Nombre":"POLOTTI","Teléfono":"5326"}',
        Registrado: '2016-01-09 00:00:00',
        Respuesta: '{"Interviniente":["FEHR","FERNANDEZ"],"Fecha":"1958-01-04 00:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'ING Y MTO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '15733',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAF-006',
        'Lugar de Servicio': 'S.E. - 4 STAND',
        Solicitante: '{"Nombre":"HUGO","Teléfono":"9902"}',
        Registrado: '2016-03-22 00:00:00',
        Respuesta: '{"Interviniente":["GOMEZ","GONZALEZ"],"Fecha":"1958-02-09 12:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'NADA',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '15502',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAF-008',
        'Lugar de Servicio': 'S.E. - 4 STAND',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"5957"}',
        Registrado: '2016-03-03 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","CORONEL"],"Fecha":"2016-03-27 12:39:08"}',
        Cierre: '{"Fecha":"2016-04-21 01:18:17","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': 'BUSCAR PERDIDAS',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '12805',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA TERMICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: '',
        'Lugar de Servicio': 'OFICINA DESARROLLO PERSONAL / ADMINISTRACION',
        Solicitante: '{"Nombre":"Laura","Teléfono":""}',
        Registrado: '2015-09-03 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","CORONEL"],"Fecha":"2015-09-05 16:56:34"}',
        Cierre: '{"Fecha":"2015-09-08 09:53:08","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'TÉRMICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '15219',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-155',
        'Lugar de Servicio': 'SE - TIRISTORES',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"3948"}',
        Registrado: '2016-03-18 00:00:00',
        Respuesta: '{"Interviniente":["ASTORE","ALVAREZ O."],"Fecha":"2016-04-04 00:53:55"}',
        Cierre: '{"Fecha":"2016-04-21 01:47:50","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '13061',
        Estado: 'Cerrada',
        Clase: 'Montaje  equipos',
        Causa: 'MONTAJE DE EQUIPO NUEVO',
        'Descripción': 'OT 13763332',
        'OT Siderar': '',
        Equipo: 'ALD-071',
        'Lugar de Servicio': 'COMEDOR PLATAFORMA 960',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":""}',
        Registrado: '2015-04-16 00:00:00',
        Respuesta: '{"Interviniente":[""],"Fecha":"2015-10-21 19:42:48"}',
        Cierre: '{"Fecha":"2016-04-27 15:25:36","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '19410',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'ALD-156',
        'Lugar de Servicio': 'COMEDOR TALLER ZONAL',
        Solicitante: '{"Nombre":"ROMERO","Teléfono":"3128"}',
        Registrado: '2017-01-19 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","REYNOSO G."],"Fecha":"2017-01-19 07:53:11"}',
        Cierre: '{"Fecha":"2017-01-19 15:46:23","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '11243',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'SIN-031',
        'Lugar de Servicio': 'S.E. - ELECTROFILTRO',
        Solicitante: '{"Nombre":"Sacco","Teléfono":"2663"}',
        Registrado: '2015-03-19 00:00:00',
        Respuesta: '{"Interviniente":["GONZALEZ","AVALOS"],"Fecha":"2015-04-25 17:38:06"}',
        Cierre: '{"Fecha":"2015-06-02 11:16:12","Usuario":"FRANQUITO"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'ELÉCTRICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20703',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAF-008',
        'Lugar de Servicio': 'S.E. - 4 STAND',
        Solicitante: '{"Nombre":"ROLANDO","Teléfono":"5957"}',
        Registrado: '2017-05-17 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","GONZALEZ"],"Fecha":"2017-05-17 18:25:44"}',
        Cierre: '{"Fecha":"2017-05-18 12:51:27","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'NADA',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '21467',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'se realiza una inspeccion general del equipo y se encuentra funcionando correctamente.',
        'OT Siderar': '',
        Equipo: 'ALD-134',
        'Lugar de Servicio': 'S.E CCM 34/35',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3138"}',
        Registrado: '2017-08-17 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","PEREZ"],"Fecha":"2017-08-17 00:00:00"}',
        Cierre: '{"Fecha":"2017-08-17 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ING Y MTO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20573',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'TCE-006',
        'Lugar de Servicio': 'TALLER BOBINADO',
        Solicitante: '{"Nombre":"FABRICIO","Teléfono":"3370"}',
        Registrado: '2017-05-02 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","FEHR"],"Fecha":"2017-05-02 19:39:17"}',
        Cierre: '{"Fecha":"2017-05-03 15:18:34","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'NADA',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '23261',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'ALD-104',
        'Lugar de Servicio': 'GRUA 174',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":""}',
        Registrado: '2017-12-29 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","GONZALEZ"],"Fecha":"2017-12-29 00:00:00"}',
        Cierre: '{"Fecha":"2017-12-29 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'NADA',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '23657',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'se controla funcionamiento, se limpia evaporador y condensadora. Se limpian filtros de aire, control de presiones. Queda en servicio.',
        'OT Siderar': 14662381,
        Equipo: 'COQ-003',
        'Lugar de Servicio': 'S.E. - ANALIZADOR DE GASES COQUERIA',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3183"}',
        Registrado: '2018-01-04 00:00:00',
        Respuesta: '{"Interviniente":["FABA","CORONEL"],"Fecha":"2018-01-04 00:00:00"}',
        Cierre: '{"Fecha":"2018-01-04 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '23312',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FALTA GAS REFRIGERANTE',
        'Descripción': 'se completa carga de gas.',
        'OT Siderar': '',
        Equipo: 'COQ-030',
        'Lugar de Servicio': 'CARRO GUIA 4',
        Solicitante: '{"Nombre":"VALDEZ","Teléfono":"3836"}',
        Registrado: '2018-01-01 00:00:00',
        Respuesta: '{"Interviniente":["BADARACCO","BASUALDO"],"Fecha":"2018-01-01 00:00:00"}',
        Cierre: '{"Fecha":"2018-01-01 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'TÉRMICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '22375',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': 'Se normaliza, se limpian filtros de aire, queda en servicio.',
        'OT Siderar': '',
        Equipo: 'ALD-083',
        'Lugar de Servicio': 'PULPITO OPERADOR CONVERTIDOR Nº2',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":"3825"}',
        Registrado: '2017-11-05 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PIERANI"],"Fecha":"2017-11-05 00:00:00"}',
        Cierre: '{"Fecha":"2017-11-05 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '11148',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FILTROS DE AIRE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'CC1-074',
        'Lugar de Servicio': 'S.E. - CCM 00 LF',
        Solicitante: '{"Nombre":"Manzoti","Teléfono":"5824"}',
        Registrado: '2015-03-13 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","ALVAREZ O."],"Fecha":"2015-03-14 17:56:23"}',
        Cierre: '{"Fecha":"2015-03-16 11:52:46","Usuario":"USUARIORANDOM"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'TÉRMICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '17737',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'ALM-001',
        'Lugar de Servicio': 'EDIFICIO ALMACENES',
        Solicitante: '{"Nombre":"PEDRO MAYI","Teléfono":"5206"}',
        Registrado: '2016-09-19 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","GONZALEZ"],"Fecha":"2016-09-19 10:50:41"}',
        Cierre: '{"Fecha":"2016-09-19 21:41:23","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'NADA',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '12831',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': 'Supuestamente hace ruido.',
        'OT Siderar': '',
        Equipo: 'AH1-007',
        'Lugar de Servicio': 'S.E. - CABRESTANTES AH1',
        Solicitante: '{"Nombre":"Noseda","Teléfono":"5853"}',
        Registrado: '2015-09-15 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","PIERANI"],"Fecha":"2015-09-15 05:01:07"}',
        Cierre: '{"Fecha":"2015-09-15 10:02:15","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'NADA',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20224',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'RED-004',
        'Lugar de Servicio': 'OFICINAS GERE ALA VIEJA',
        Solicitante: '{"Nombre":"GUZMAN","Teléfono":"5212"}',
        Registrado: '2017-03-20 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","GALASSI"],"Fecha":"2017-03-20 16:46:53"}',
        Cierre: '{"Fecha":"2017-03-21 09:33:47","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'NADA',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '11108',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PERDIDA DE GAS',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'ALD-094',
        'Lugar de Servicio': 'GRUA 155',
        Solicitante: '{"Nombre":"Mariano","Teléfono":"3825"}',
        Registrado: '2015-03-11 00:00:00',
        Respuesta: '{"Interviniente":["CORONEL","OJEDA"],"Fecha":"2015-03-13 16:50:07"}',
        Cierre: '{"Fecha":"2015-03-16 09:40:14","Usuario":"MALAMIA"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'TÉRMICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '14427',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAF-115',
        'Lugar de Servicio': 'S.E. - ESTAÑADO ELECTROLITICO',
        Solicitante: '{"Nombre":"SANCHEZ","Teléfono":"5957"}',
        Registrado: '2015-12-31 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2016-02-28 07:44:33"}',
        Cierre: '{"Fecha":"2016-04-27 15:29:06","Usuario":"MALAMIA"}',
        Supervisor: 'ALVAREZ M., MAURICIO RAMON',
        'Causa General': 'ELÉCTRICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '16329',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 13963532,
        Equipo: 'CC2-033',
        'Lugar de Servicio': 'SALA TIJERAS/DRIVE DE GRUAS CC2',
        Solicitante: '{"Nombre":"SOLA","Teléfono":""}',
        Registrado: '2015-11-13 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2016-02-08 20:45:56"}',
        Cierre: '{"Fecha":"2016-05-06 17:31:51","Usuario":"MALAMIA"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'ING Y MTO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '13869',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'ALD-135',
        'Lugar de Servicio': 'S.E. CCM 15/24',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":""}',
        Registrado: '2015-11-30 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","FABA"],"Fecha":"2016-02-12 18:57:17"}',
        Cierre: '{"Fecha":"2016-04-27 13:54:34","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22729',
        Estado: 'Abierta',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'Se cambian los contactores del condensador. Se le ajusta refrigerante. Se buscan perdidas, no visibles.',
        'OT Siderar': '',
        Equipo: 'MAR-003',
        'Lugar de Servicio': 'OFICINA GERENTE MARE',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3183"}',
        Registrado: '2017-11-15 00:00:00',
        Respuesta: '{"Interviniente":["CAMPILONGO","GUERREIRO"],"Fecha":"1958-12-08 00:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '11148',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FILTROS DE AIRE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'CC1-074',
        'Lugar de Servicio': 'S.E. - CCM 00 LF',
        Solicitante: '{"Nombre":"Manzoti","Teléfono":"5824"}',
        Registrado: '2015-03-13 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","ALVAREZ O."],"Fecha":"2015-03-14 17:56:23"}',
        Cierre: '{"Fecha":"2015-03-16 11:52:46","Usuario":"USUARIORANDOM"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'TÉRMICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '23577',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-006',
        'Lugar de Servicio': 'S.E. - CCM ASPIRADORES',
        Solicitante: '{"Nombre":"BORRAS","Teléfono":"5782"}',
        Registrado: '2018-01-12 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","HINOJOSA"],"Fecha":"2018-01-12 00:00:00"}',
        Cierre: '{"Fecha":"2018-01-12 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'NADA',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '23601',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'se encuentra térmica baja, con un corto circuito en bornera. Se repone queda en servicio.',
        'OT Siderar': 14576689,
        Equipo: 'CEN-035',
        'Lugar de Servicio': 'PREPARACION  DE SANWICH',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3183"}',
        Registrado: '2017-12-29 00:00:00',
        Respuesta: '{"Interviniente":["CAMPILONGO","GUERREIRO"],"Fecha":"2018-06-29 12:00:00"}',
        Cierre: '{"Fecha":"2018-12-29 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '14946',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FALTA GAS REFRIGERANTE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-036',
        'Lugar de Servicio': 'COMEDOR BATERIA 1',
        Solicitante: '{"Nombre":"TORRES","Teléfono":"3836"}',
        Registrado: '2016-01-22 00:00:00',
        Respuesta: '{"Interviniente":["PERAZZOLO S.","LOPEZ A."],"Fecha":"2016-03-10 07:46:40"}',
        Cierre: '{"Fecha":"2016-04-27 15:33:20","Usuario":"FRANQUITO"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'TÉRMICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '11654',
        Estado: 'Cerrada',
        Clase: 'Preventivo',
        Causa: 'PREVENTIVO',
        'Descripción': 'OT 13748303 - LLEVAR MANGUERA PARA SOPLETEAR EL SECTOR PROVEERA LOS FILTROS',
        'OT Siderar': '',
        Equipo: 'CC2-030',
        'Lugar de Servicio': 'LIMAB COLADA CONTINUA 2',
        Solicitante: '{"Nombre":"SANCHEZ","Teléfono":"3306"}',
        Registrado: '2015-04-24 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","BOGADO M."],"Fecha":"2015-04-24 17:30:54"}',
        Cierre: '{"Fecha":"2015-04-25 11:01:48","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'PREVENCION',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '18443',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FILTROS DE AIRE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-041',
        'Lugar de Servicio': 'GRUA 114',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"5448"}',
        Registrado: '2016-11-22 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PIERANI"],"Fecha":"2016-11-22 19:38:03"}',
        Cierre: '{"Fecha":"2016-11-23 15:16:06","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'TÉRMICO',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22011',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'Se hace una inspeccion general del equipo y control de funcionamiento.',
        'OT Siderar': 14479204,
        Equipo: 'RED-004',
        'Lugar de Servicio': 'OFICINAS GERE ALA VIEJA',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3138"}',
        Registrado: '2017-09-28 00:00:00',
        Respuesta: '{"Interviniente":["CAMPILONGO","GUERREIRO"],"Fecha":"2017-09-28 00:00:00"}',
        Cierre: '{"Fecha":"2017-09-28 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '17226',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAF-004',
        'Lugar de Servicio': 'S.E. - 4 STAND',
        Solicitante: '{"Nombre":"INTENDENCIA","Teléfono":"261*3183"}',
        Registrado: '2016-08-08 00:00:00',
        Respuesta: '{"Interviniente":["FABA","SERRANO"],"Fecha":"2016-09-13 20:27:57"}',
        Cierre: '{"Fecha":"2016-10-20 16:55:54","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ING Y MTO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '21120',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 14153646,
        Equipo: 'INT-005',
        'Lugar de Servicio': 'INTENDENCIA PLANTA BAJA',
        Solicitante: '{"Nombre":"ESCALANTE","Teléfono":""}',
        Registrado: '2017-07-18 00:00:00',
        Respuesta: '{"Interviniente":["FLOREANI","ANTICHI"],"Fecha":"2017-07-18 04:04:50"}',
        Cierre: '{"Fecha":"2017-07-18 08:09:41","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '23821',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA MECANICO',
        'Descripción': 'se cambian correas, queda en servicio.',
        'OT Siderar': '',
        Equipo: 'CC1-011',
        'Lugar de Servicio': 'S.E. INSTRUMENTAL CC1',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":"5366"}',
        Registrado: '2018-01-24 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","ALVAREZ L."],"Fecha":"2018-01-24 00:00:00"}',
        Cierre: '{"Fecha":"2018-01-24 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'MECÁNICO',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '16704',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-027',
        'Lugar de Servicio': 'CARRO GUIA 4',
        Solicitante: '{"Nombre":"SOBERANO","Teléfono":"261*3836"}',
        Registrado: '2016-06-21 00:00:00',
        Respuesta: '{"Interviniente":["BADARACCO","BASUALDO"],"Fecha":"2016-06-21 06:29:08"}',
        Cierre: '{"Fecha":"2016-06-21 12:58:17","Usuario":"USUARIORANDOM"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'ELÉCTRICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '21005',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAF-113',
        'Lugar de Servicio': 'S.E. - ENTRADA DECAPADO',
        Solicitante: '{"Nombre":"ROLANDO","Teléfono":"5957"}',
        Registrado: '2017-07-01 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","GONZALEZ"],"Fecha":"2017-07-02 16:04:15"}',
        Cierre: '{"Fecha":"2017-07-04 08:08:31","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 1,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '24552',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'se cambian correas de la torre y se tensa la misma. (A104)',
        'OT Siderar': 14959592,
        Equipo: 'TCE-002',
        'Lugar de Servicio': 'ENFRIADOR DE AGUA - TALLER CENTRAL',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3183"}',
        Registrado: '2018-02-21 00:00:00',
        Respuesta: '{"Interviniente":["CARBONE","CORONEL"],"Fecha":"2018-02-21 00:00:00"}',
        Cierre: '{"Fecha":"2018-02-21 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '17376',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FALTA GAS REFRIGERANTE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'ALD-106',
        'Lugar de Servicio': 'OFICINA PANTOGRAFO',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"4136"}',
        Registrado: '2016-08-20 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PIERANI"],"Fecha":"2016-08-21 07:57:55"}',
        Cierre: '{"Fecha":"2016-08-22 15:55:51","Usuario":"MALAMIA"}',
        Supervisor: 'ALVAREZ M., MAURICIO RAMON',
        'Causa General': 'TÉRMICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '16793',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA MECANICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-021',
        'Lugar de Servicio': 'CARRO DE CARGA 5',
        Solicitante: '{"Nombre":"SUP.","Teléfono":"3836"}',
        Registrado: '2016-06-28 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","FLOREANI"],"Fecha":"2016-06-28 10:42:35"}',
        Cierre: '{"Fecha":"2016-06-28 21:25:10","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'MECÁNICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '21273',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'limpieza de filtros, reparacion de falso contacto, seteo de termostato, control de carga de refrigerante y control de funcionamiento.',
        'OT Siderar': '',
        Equipo: 'MAR-004',
        'Lugar de Servicio': 'TALLER DE MARE',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3138"}',
        Registrado: '2017-08-01 00:00:00',
        Respuesta: '{"Interviniente":["ANTICHI","CAMPILONGO"],"Fecha":"2017-08-17 05:51:12"}',
        Cierre: '{"Fecha":"2017-09-02 11:42:25","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 4,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22700',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': 'Se habilitan ambos circuitos. Queda en servicio.',
        'OT Siderar': '',
        Equipo: 'SIN-027',
        'Lugar de Servicio': 'S.E. - VENTILADOR PRINCIPAL',
        Solicitante: '{"Nombre":"JULIO","Teléfono":"4021"}',
        Registrado: '2017-11-29 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","BADARACCO"],"Fecha":"2017-11-29 00:00:00"}',
        Cierre: '{"Fecha":"2017-11-29 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '15202',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-084',
        'Lugar de Servicio': 'S.E. - ENFRIADORES PRIMARIOS 2 MC 16',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"5782"}',
        Registrado: '2016-02-10 00:00:00',
        Respuesta: '{"Interviniente":["ALVAREZ O.","UDUT"],"Fecha":"2016-03-18 01:50:10"}',
        Cierre: '{"Fecha":"2016-04-24 03:40:21","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '16841',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'CC1-014',
        'Lugar de Servicio': 'S.E. INSTRUMENTAL CC1',
        Solicitante: '{"Nombre":"FERRATO","Teléfono":"3403"}',
        Registrado: '2016-07-02 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","GONZALEZ"],"Fecha":"2016-07-08 05:39:42"}',
        Cierre: '{"Fecha":"2016-07-14 11:19:24","Usuario":"FRANQUITO"}',
        Supervisor: 'ALVAREZ M., MAURICIO RAMON',
        'Causa General': 'ELÉCTRICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '17630',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'MANTENIMIENTO SIN OT SIDERAR',
        'OT Siderar': '',
        Equipo: 'LAF-028',
        'Lugar de Servicio': 'CASILLA DE VIGILANCIA CHAPA NAVAL',
        Solicitante: '{"Nombre":"PLAN","Teléfono":""}',
        Registrado: '2016-09-08 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","BADARACCO"],"Fecha":"2016-09-08 06:53:34"}',
        Cierre: '{"Fecha":"2016-09-08 13:47:08","Usuario":"FRANQUITO"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'ING Y MTO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '19141',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'CC1-051',
        'Lugar de Servicio': 'GRUA 191',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"4136"}',
        Registrado: '2017-01-02 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","MARCHIANO"],"Fecha":"2017-01-02 19:12:00"}',
        Cierre: '{"Fecha":"2017-01-03 14:24:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '15391',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-032',
        'Lugar de Servicio': 'CARRO GUIA 5',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"3836"}',
        Registrado: '2016-02-23 00:00:00',
        Respuesta: '{"Interviniente":["MORANDIN","RIOS"],"Fecha":"2016-03-26 00:28:59"}',
        Cierre: '{"Fecha":"2016-04-27 00:57:58","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ELÉCTRICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '15565',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'RED-004',
        'Lugar de Servicio': 'OFICINAS GERE ALA VIEJA',
        Solicitante: '{"Nombre":"MARTINES","Teléfono":"4031"}',
        Registrado: '2016-03-03 00:00:00',
        Respuesta: '{"Interviniente":["FABA","BOGADO G."],"Fecha":"1958-01-31 00:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"FRANQUITO"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'ELÉCTRICO',
        Horas: 3,
        'Tareas Pendientes': 'COLOCAR FILTROS FALTANTES,POSIBLE PERDIDA DE GAS',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '17266',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 14059802,
        Equipo: 'TCE-001',
        'Lugar de Servicio': 'CENTRAL EX GERENCIA MECANICA',
        Solicitante: '{"Nombre":"ESCALANTE","Teléfono":""}',
        Registrado: '2016-08-11 00:00:00',
        Respuesta: '{"Interviniente":["CORONEL","SCHIEL"],"Fecha":"2016-09-01 19:31:27"}',
        Cierre: '{"Fecha":"2016-09-23 15:02:54","Usuario":"USUARIORANDOM"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 2,
        'Tareas Pendientes': 'Pintar',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '23384',
        Estado: 'Abierta',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'se arma equipo que estaba desarmado por falta de un compresor. Queda funcionando con un solo sistema.',
        'OT Siderar': 14435210,
        Equipo: 'SIS-024',
        'Lugar de Servicio': 'SALA UPS',
        Solicitante: '{"Nombre":"intendencia","Teléfono":"3183"}',
        Registrado: '2017-12-22 00:00:00',
        Respuesta: '{"Interviniente":["CAMPILONGO","GUERREIRO"],"Fecha":"1958-12-26 12:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '12321',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': 'OT 13864898',
        'OT Siderar': '',
        Equipo: 'LAF-147',
        'Lugar de Servicio': 'OFICINA MASI FRIO',
        Solicitante: '{"Nombre":"OSCAR BUSTOS","Teléfono":"3496"}',
        Registrado: '2015-07-17 00:00:00',
        Respuesta: '{"Interviniente":["FLOREANI","SERRANO"],"Fecha":"2015-07-17 08:34:28"}',
        Cierre: '{"Fecha":"2015-07-17 17:08:55","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20405',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 14434412,
        Equipo: 'COQ-085',
        'Lugar de Servicio': 'S.E. - ENFRIADORES PRIMARIOS 2 MC 16',
        Solicitante: '{"Nombre":"ESCALANTE","Teléfono":""}',
        Registrado: '2017-04-11 00:00:00',
        Respuesta: '{"Interviniente":["CORONEL","FLOREANI"],"Fecha":"2017-04-11 07:58:00"}',
        Cierre: '{"Fecha":"2017-04-11 15:56:00","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '14093',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PROBLEMA ELECTRICO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'PSR-001',
        'Lugar de Servicio': 'PORTERIA SUR',
        Solicitante: '{"Nombre":"FERNANDEZ","Teléfono":"5703"}',
        Registrado: '2015-12-16 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","FERNANDEZ"],"Fecha":"1957-12-23 00:00:00"}',
        Cierre: '{"Fecha":"1900-01-00 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'FABBRI, CLAUDIO CESAR',
        'Causa General': 'ELÉCTRICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '22720',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'NINGUNA FALLA',
        'Descripción': 'Se va al lugar, se encuentra equipos funcionando y sala fresca. Se le da aviso al supervisor.',
        'OT Siderar': '',
        Equipo: '',
        'Lugar de Servicio': 'PLANTA DE AGUA / TORRE 4000',
        Solicitante: '{"Nombre":"Supervisor","Teléfono":"5782"}',
        Registrado: '2017-11-30 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PERAZZOLO S."],"Fecha":"2017-11-30 00:00:00"}',
        Cierre: '{"Fecha":"2017-11-30 00:00:00","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'NADA',
        Horas: 6,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '15248',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FALTA GAS REFRIGERANTE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-125',
        'Lugar de Servicio': 'SE - BOBINADORA',
        Solicitante: '{"Nombre":"DE LAS MARCEDES","Teléfono":"3300"}',
        Registrado: '2016-02-12 00:00:00',
        Respuesta: '{"Interviniente":["BASUALDO","UDUT"],"Fecha":"2016-03-19 01:45:39"}',
        Cierre: '{"Fecha":"2016-04-24 03:31:17","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'TÉRMICO',
        Horas: 0,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '23819',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EVAPORADOR SUCIO',
        'Descripción': 'se sacan filtros, se limpian y se deja equipo descongelando. Se habilita y se deja en servicio.',
        'OT Siderar': '',
        Equipo: 'ALD-101',
        'Lugar de Servicio': 'GRUA 169',
        Solicitante: '{"Nombre":"PABLO","Teléfono":"5877"}',
        Registrado: '2018-01-23 00:00:00',
        Respuesta: '{"Interviniente":["TARRAGONA","GONZALEZ"],"Fecha":"2018-01-23 00:00:00"}',
        Cierre: '{"Fecha":"2018-01-23 00:00:00","Usuario":"USUARIORANDOM"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'TÉRMICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '20872',
        Estado: 'Cerrada',
        Clase: 'Mantenimiento',
        Causa: 'MANTENIMIENTO',
        'Descripción': '',
        'OT Siderar': 14370016,
        Equipo: 'COQ-056',
        'Lugar de Servicio': 'LOCOMOTORA 20 - VAGON DE APAGADO',
        Solicitante: '{"Nombre":"ESCALANTE","Teléfono":""}',
        Registrado: '2017-06-10 00:00:00',
        Respuesta: '{"Interviniente":["CORONEL","GUERREIRO"],"Fecha":"2017-06-10 04:29:14"}',
        Cierre: '{"Fecha":"2017-06-10 08:58:28","Usuario":"MALAMIA"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'ING Y MTO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '11007',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'PERDIDA DE GAS',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'MAR-005',
        'Lugar de Servicio': 'OFICINAS PREVENTIVO MARE',
        Solicitante: '{"Nombre":"Fragazzini","Teléfono":""}',
        Registrado: '2015-03-05 00:00:00',
        Respuesta: '{"Interviniente":["GONZALEZ","ARMOA"],"Fecha":"2015-03-07 16:01:30"}',
        Cierre: '{"Fecha":"2015-03-10 08:02:59","Usuario":"MALAMIA"}',
        Supervisor: 'DOTAVIO, GONZALO',
        'Causa General': 'TÉRMICO',
        Horas: 5,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      },
      {
        'Código': '20021',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'FILTROS DE AIRE',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'COQ-063',
        'Lugar de Servicio': 'OFICINA PREVENTIVO',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"4471"}',
        Registrado: '2017-03-06 00:00:00',
        Respuesta: '{"Interviniente":["LOPEZ A.","PIERANI"],"Fecha":"2017-03-06 17:06:12"}',
        Cierre: '{"Fecha":"2017-03-07 10:12:25","Usuario":"FRANQUITO"}',
        Supervisor: 'TOGNETTI, JOSÉ',
        'Causa General': 'TÉRMICO',
        Horas: 3,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'NO'
      },
      {
        'Código': '19164',
        Estado: 'Cerrada',
        Clase: 'Reclamo',
        Causa: 'EQUIPO DESHABILITADO',
        'Descripción': '',
        'OT Siderar': '',
        Equipo: 'LAC-046',
        'Lugar de Servicio': 'PULPITO BOBINADORA',
        Solicitante: '{"Nombre":"SUPERVISOR","Teléfono":"5841"}',
        Registrado: '2017-01-04 00:00:00',
        Respuesta: '{"Interviniente":["FEHR"],"Fecha":"2017-01-04 16:55:55"}',
        Cierre: '{"Fecha":"2017-01-05 09:51:50","Usuario":"FRANQUITO"}',
        Supervisor: 'MELGAREJO, ARIEL',
        'Causa General': 'ELÉCTRICO',
        Horas: 2,
        'Tareas Pendientes': '',
        'Pasado a Mantenimiento': 'FALSO',
        'Conformidad Cliente': 'SI'
      }
    ]
}

function checkNotRepeat(arrayObj){
  var notRepeated = []
  var repeated = []
  for(let i =0;i<arrayObj.length;i++){
      const  code=arrayObj[i]['Código']
      if (notRepeated.includes(code)){
          repeated.push(code)
      }else{
          notRepeated.push(code)
      }
  }
  if(repeated.length==0){
      return 'ningún código se repite'
  }else{
      console.log('se repiten:')
      return (repeated)
  }
}
export default BASE